theme = "apollo"

base_url = "https://majabojarska.dev/"
title = "Maja Bojarska"
description = "Maja's engineering blog"
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

# The theme supports feeds (RSS and ATOM)
generate_feeds = true
# Use `rss.xml` for RSS feeds and `atom.xml` for ATOM.
feed_filenames = ["rss.xml", "atom.xml"]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[link_checker]
internal_level = "error"
external_level = "error"

[markdown]
insert_anchor_links = "none"
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "material-dark", filename = "syntax-theme-dark.css" },
    { theme = "material-light", filename = "syntax-theme-light.css" },
]
render_emoji = true
smart_punctuation = true
lazy_async_image = true
bottom_footnotes = false

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"                    # light, dark, auto, toggle
fancy_code = true
dynamic_note = true                 # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true

menu = [
    { name = "/devlog", url = "/devlog", weight = 1 },
    { name = "/posts", url = "/posts", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/cat", url = "/cat", weight = 4 },
    { name = "/tags", url = "/tags", weight = 5 },
]

socials = [
    { name = "github", url = "https://github.com/majabojarska", icon = "github", newtab = true },
    { name = "linkedin", url = "https://linkedin.com/in/majabojarska", icon = "linkedin", newtab = true },
    { name = "mastodon", url = "https://mastodon.social/@majabojarska", icon = "mastodon", newtab = true },
]

stylesheets = [
    # "custom.css"    # at /static/custom.css
]

[extra.analytics]
enabled = false
