theme = "apollo"

base_url = "https://majabojarska.dev"
title = "Maja Bojarska"
description = "Maja's Devlog"
compile_sass = true
minify_html = true

taxonomies = [
    {name = "tags"}
]

# The theme supports feeds (RSS and ATOM)
generate_feeds = true
# Use `rss.xml` for RSS feeds and `atom.xml` for ATOM.
feed_filenames = ["rss.xml", "atom.xml"]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

# [markdown]
# highlight_code = true
# highlight_theme = "boron"

[extra]


toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/not-matthias/apollo/tree/main/content/"

menu = [
    { name = "/devlog", url = "/devlog", weight = 1 },
    { name = "/posts", url = "/posts", weight = 2 },
    # { name = "/about", url = "/about", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 },
]

socials = [
    {name = "github", url = "https://github.com/majabojarska", icon="github", newtab = true},
    {name = "linkedin", url = "https://linkedin.com/in/majabojarska", icon="linkedin", newtab = true},
    {name = "mastodon", url = "https://mastodon.social/@majabojarska", icon="mastodon", newtab = true},
]

stylesheets = [
    # "custom.css"    # at /static/custom.css
]

[extra.analytics]
enabled = false

[extra.analytics.goatcounter]
user = "your_user"
host = "example.com" # default= goatcounter.com

[extra.analytics.umami]
website_id = "43929cd1-1e83...."
host_url = "https://stats.mywebsite.com" # default: https://api-gateway.umami.dev/


# # One of: blue, green, orange, pink, red.
# # Defaults to blue.
# # Append -light for light themes, e.g. blue-light
# # Or append -auto, e.g. blue-auto
# accent_color = "orange-light"

# # One of: blue, dark, green, orange, pink, red, light, auto
# # Enabling dark background will also modify primary font color to be darker.
# # Defaults to accent color (or, if not accent color specified, to blue).
# background_color = "light"

# # The logo text - defaults to "Terminimal theme"
# logo_text = "Maja Bojarska"

# # The logo link - defaults to base_url.
# #logo_home_link = "/take/me/away!"

# # Author name: when specified, modifies the default
# # copyright text. Apart from author, it will
# # contain current year and a link to the theme.
# author = "Maja Bojarska"

# # Copyright text in HTML format. If specified,
# # entirely replaces default copyright and author.
# #copyright_html = "My custom&nbsp;<b>copyright</b>"

# # menu is enabled by adding menu_items (optional)
# menu_items = [
#     # each of these is optional, name and url are required
#     # $BASE_URL is going to be substituted by base_url from configuration
#     {name = "blog", url = "$BASE_URL"},

#     # tags should only be enabled if you have "tags" taxonomy
#     # see documentation below for more details
#     {name = "tags", url = "$BASE_URL/tags"},
#     {name = "archive", url = "$BASE_URL/archive"},
#     # {name = "about me", url = "$BASE_URL/about"},

#     # set newtab to true to make the link open in new tab
#     {name = "github", url = "https://github.com/majabojarska", newtab = true},
#     {name = "linkedin", url = "https://linkedin.com/in/majabojarska", newtab = true},
# ]

# # Whether to show links to earlier and later (aka. higher/lower) posts
# # on each post page (defaults to true).
# enable_post_view_navigation = true

# # The text shown at the bottom of a post,
# # before earlier/later post links.
# # Defaults to "Thanks for reading! Read other posts?"
# post_view_navigation_prompt = "Thanks for reading! Read other posts?"

# # Use full Hack character set, not just a subset.
# # Switch this to true if you need full unicode support.
# # Defaults to false.
# use_full_hack_font = false

# # Optional: Global favicon URL and mimetype.
# #           Mimetype defaults to "image/x-icon".
# #           The URL should point at a file located
# #           in your site's "static" directory.
# # favicon = "/favicon.png"
# # favicon_mimetype = "image/png"

# # Optional: Set how <title> elements are rendered.
# # Values:
# # - "main_only" -- only the main title (`config.title`) is rendered.
# # - "page_only" -- only the page title (if defined) is rendered,
# #                  falling back to `config.title` if not defined or empty.
# # - "combined" -- combine like so: "page_title | main_title",
# #                 or if page_title is not defined or empty, fall back to `main_title`
# #
# # Note that the main (index) page only has the main title.
# page_titles = "main_only"

# # Optional: default image to use for OpenGraph.
# #           If the page doesnt set og_image, use this one as fallback. Usefull
# #           for indexes and taxonomies' pages.
# #default_og_image = "static/ocean.jpg"
